name: TaskRunner
version: 1.0
main: com.brandonjja.taskRun.TaskRun
author: Brandonjja
description: TaskRunner
commands:
    newgame:
        usage: /newgame
        description: Starts a new game
    tasks:
        usage: /tasks
        description: Displays a list of tasks to do
    toggletasks:
        usage: /toggletasks
        description: Toggles the side task bar
    tt:
        usage: /tt
        description: Toggles the side task bar (same as /toggletasks)
    back:
        usage: /back
        description: Teleports you to your previous location after TPing
    pause:
        usage: /pause
        description: Pause or unpauses the game
    nostop:
        usage: /nostop
        description: Stops the auto reboot
permissions:
    taskrunner.*:
        children:
            taskrunner.newgame: true
            taskrunner.back: true
            taskrunner.pause: true
    taskrunner.newgame:
        default: op
    taskrunner.back:
        default: op
    taskrunner.pause:
        default: op